version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app  
    overwrite: yes
hooks:
  BeforeInstall:
    - location: before_install.sh 
      timeout: 600
      runas: root
  AfterInstall:
    - location: after_install.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: application_start.sh
      timeout: 600
      runas: root
  ApplicationStop:
    - location: application_stop.sh
      timeout: 600
      runas: root
