version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.21
    commands:
      - echo "Verifying Go installation..."
      - go version || { echo "Go installation failed!"; exit 1; }
      - go env
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - go mod download
  build:
    commands:
      - echo "Building binary..."
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o app1 app/main.go
      - sudo chmod +x app
  post_build:
    commands:
      - echo "Packaging artifacts..."
      # Create structured deployment package
      - sudo tar -czvf app.tar.gz app1 appspec.yml scripts/
      - aws s3 cp app.tar.gz s3://tracker-backend-deploy/app-$CODEBUILD_BUILD_NUMBER.tar.gz
artifacts:
  files:
    - app.tar.gz
  discard-paths: yes



# Might beb that i dont sudo chmod +x to make the app.tar.gz executable
 
# This is strange after extracting
#app/
#app/main.go
#app/main
#appspec.yml
#scripts/
#scripts/after_install.sh
#scripts/application_stop.sh
#scripts/before_install.sh
#scripts/start_application.sh
#
#