# Dockerfile (for production/Kubernetes)
FROM golang:1.23-alpine AS builder

WORKDIR /app

# Cache dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

COPY scripts/ ./scripts/
RUN chmod +x ./scripts/sqs_init.sh
RUN chmod +x ./scripts/s3_init.sh

# Build the binary
RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -tags netgo -o main ./app/main.go

# Create minimal runtime image
FROM alpine:latest

RUN apk --no-cache add ca-certificates postgresql-client

WORKDIR /app


# Copy the binary from builder
COPY --from=builder /app/main /app/main

# Copy sql files
COPY --from=builder /app/database/*.sql ./database/

# Copy .env file if needed
COPY .env.development .

# Grant permissions
RUN chmod +x /app/main

EXPOSE 3333

# Run the binary
CMD ["/app/main"]